## リポジトリ登録
- name: "Install jenkins yum repository"
  yum_repository:
    name: jenkins
    description: "jenkins YUM repo"
    baseurl: "http://pkg.jenkins-ci.org/redhat-stable/"

- name: "Install jenkins-ci.org.key"
  rpm_key:
    key: "http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key"

## インストール
- name: "Install Jenkins"
  yum:
    name: jenkins
